class Frases {
  static List frases = [
    {"frase": "Nunca deixe ninguém te dizer que não pode fazer alguma coisa. Se você tem um sonho tem que correr atrás dele. As pessoas não conseguem vencer e dizem que você também não vai vencer. Se você quer uma coisa corre atrás.", "autor": "À Procura da Felicidade", "likes": 95, "liked": false, "comments": 32, "retweets": 95},
    {"frase": "As pessoas costumam dizer que a motivação não dura sempre. Bem, nem o efeito do banho, por isso recomenda-se diariamente.", "autor": "Zig Ziglar", "likes": 22, "liked": false, "comments": 7, "retweets": 48},
    {"frase": "Motivação é a arte de fazer as pessoas fazerem o que você quer que elas façam porque elas o querem fazer.", "autor": "Dwight Eisenhower", "likes": 37, "liked": true, "comments": 35, "retweets": 64},
    {"frase": "Toda ação humana, quer se torne positiva ou negativa, precisa depender de motivação.", "autor": "Dalai Lama", "likes": 40, "liked": true, "comments": 8, "retweets": 23},
    {"frase": "A verdadeira motivação vem de realização, desenvolvimento pessoal, satisfação no trabalho e reconhecimento.", "autor": "Frederick Herzberg", "likes": 77, "liked": true, "comments": 73, "retweets": 34},
    {"frase": "A amizade desenvolve a felicidade e reduz o sofrimento, duplicando a nossa alegria e dividindo a nossa dor.", "autor": "Joseph Addison", "likes": 83, "liked": false, "comments": 93, "retweets": 51},
    {"frase": "Saber encontrar a alegria na alegria dos outros é o segredo da felicidade.", "autor": "Georges Bernanos", "likes": 84, "liked": true, "comments": 19, "retweets": 26},
    {"frase": "A alegria de fazer o bem é a única felicidade verdadeira.", "autor": "Leon Tolstói", "likes": 82, "liked": false, "comments": 93, "retweets": 76},
    {"frase": "O segredo da felicidade é encontrar a nossa alegria na alegria dos outros.", "autor": "Alexandre Herculano", "likes": 50, "liked": true, "comments": 53, "retweets": 83},
    {"frase": "A verdadeira felicidade vem da alegria de atos bem feitos, do sabor de criar coisas renovadas.", "autor": "Antoine de Saint-Exupéry", "likes": 9, "liked": false, "comments": 50, "retweets": 69},
    {"frase": "Uma alegria tumultuosa anuncia uma felicidade medíocre e breve.", "autor": "Plutarco", "likes": 32, "liked": false, "comments": 75, "retweets": 25},
    {"frase": "Ser feliz sem motivo é a mais autêntica forma de felicidade.", "autor": "Carlos Drummond de Andrade", "likes": 57, "liked": true, "comments": 14, "retweets": 54},
    {"frase": "Não existe um caminho para a felicidade. A felicidade é o caminho.", "autor": "Thich Nhat Hanh", "likes": 52, "liked": false, "comments": 87, "retweets": 46},
    {"frase": "Muitas pessoas perdem as pequenas alegrias enquanto aguardam a grande felicidade.", "autor": "Pearl S. Buck", "likes": 60, "liked": true, "comments": 18, "retweets": 49},
    {"frase": "A alegria evita mil males e prolonga a vida.", "autor": "William Shakespeare", "likes": 58, "liked": false, "comments": 38, "retweets": 69},
    {"frase": "A alegria está na luta, na tentativa, no sofrimento envolvido e não na vitória propriamente dita.", "autor": "Mahatma Gandhi", "likes": 7, "liked": true, "comments": 92, "retweets": 46},
    {"frase": "Aquele que nunca viu a tristeza, nunca reconhecerá a alegria.", "autor": "Khalil Gibran", "likes": 72, "liked": false, "comments": 57, "retweets": 78},
    {"frase": "Dialética. É claro que a vida é boa. E a alegria, a única indizível emoção. É claro que te acho linda. Em ti bendigo o amor das coisas simples. É claro que te amo. E tenho tudo para ser feliz. Mas acontece que eu sou triste...", "autor": "Vinicius de Moraes", "likes": 26, "liked": false, "comments": 40, "retweets": 23},
    {"frase": "A alegria não está nas coisas, está em nós.", "autor": "Charles Wagner", "likes": 98, "liked": false, "comments": 40, "retweets": 58},
    {"frase": "Deus nunca perturba a alegria dos seus filhos se não for para lhes preparar uma mais certa e maior.", "autor": "Alessandro Manzoni", "likes": 72, "liked": false, "comments": 11, "retweets": 29},
    {"frase": "Não há satisfação maior do que aquela que sentimos quando proporcionamos alegria aos outros.", "autor": "Masaharu Taniguchi", "likes": 67, "liked": true, "comments": 90, "retweets": 40},
    {"frase": "Não há arauto mais perfeito da alegria do que o silêncio. Eu sentir-me-ia muito pouco feliz se me fosse possível dizer a que ponto o sou.", "autor": "William Shakespeare", "likes": 50, "liked": true, "comments": 1, "retweets": 64},
    {"frase": "Sofremos muito com o pouco que nos falta e gozamos pouco o muito que temos.", "autor": "William Shakespeare", "likes": 69, "liked": false, "comments": 16, "retweets": 33},
    {"frase": "Toda a poesia - e a canção é uma poesia ajudada - reflete o que a alma não tem. Por isso a canção dos povos tristes é alegre e a canção dos povos alegres é triste.", "autor": "Fernando Pessoa", "likes": 88, "liked": false, "comments": 1, "retweets": 26},
    {"frase": "Eu faço da dificuldade a minha motivação. A volta por cima vem na continuação.", "autor": "Charlie Brown Jr", "likes": 48, "liked": false, "comments": 62, "retweets": 92},
    {"frase": "Minha energia é o desafio, minha motivação é o impossível, e é por isso que eu preciso ser, à força e a esmo, inabalável.", "autor": "Augusto Branco", "likes": 30, "liked": true, "comments": 2, "retweets": 33},
    {"frase": "Faça o que for necessário para ser feliz. Mas não se esqueça que a felicidade é um sentimento simples, você pode encontrá-la e deixá-la ir embora por não perceber sua simplicidade.", "autor": "Martha Medeiros", "likes": 19, "liked": false, "comments": 87, "retweets": 86},
    {"frase": "Por detrás da alegria e do riso, pode haver uma natureza vulgar, dura e insensível. Mas, por detrás do sofrimento, há sempre sofrimento. Ao contrário do prazer, a dor não tem máscara.", "autor": "Oscar Wilde", "likes": 53, "liked": false, "comments": 20, "retweets": 66},
    {"frase": "Deus nos dá pessoas e coisas, para aprendermos a alegria... Depois, retoma coisas e pessoas para ver se já somos capazes da alegria sozinhos... Essa... a alegria que ele quer", "autor": "Guimarães Rosa", "likes": 13, "liked": false, "comments": 77, "retweets": 13},
    {"frase": "Na ética o mal é uma consequência do bem, assim, na realidade da alegria nasce a tristeza. Ou a lembrança da felicidade passada é a angústia de hoje, ou as agonias que são tem sua origem nos êxtases que poderiam ter sido.", "autor": "Edgar Allan Poe", "likes": 70, "liked": true, "comments": 6, "retweets": 16},
    {"frase": "Não preciso me drogar para ser um gênio; Não preciso ser um gênio para ser humano; Mas preciso do seu sorriso para ser feliz.", "autor": "Charles Chaplin", "likes": 36, "liked": false, "comments": 2, "retweets": 73},
    {"frase": "A alegria que se tem em pensar e aprender faz-nos pensar e aprender ainda mais.", "autor": "Aristóteles", "likes": 53, "liked": false, "comments": 66, "retweets": 45},
    {"frase": "Para o trabalho que gostamos, levantamo-nos cedo e fazêmo-lo com alegria.", "autor": "William Shakespeare", "likes": 89, "liked": false, "comments": 84, "retweets": 72},
    {"frase": "A todos os que sofrem e estão sós, dai sempre um sorriso de alegria. Não lhes proporciones apenas os vossos cuidados, mas também o vosso coração.", "autor": "Madre Teresa de Calcutá", "likes": 72, "liked": false, "comments": 75, "retweets": 71},
    {"frase": "Para quem ama, qualquer sacrifício é alegria.", "autor": "Benjamin Franklin", "likes": 24, "liked": true, "comments": 60, "retweets": 71},
    {"frase": "A gaveta da alegria já está cheia de ficar vazia", "autor": "Alice Ruiz", "likes": 81, "liked": false, "comments": 55, "retweets": 0},
    {"frase": "Há mais, muito mais, para o Natal do que luz de vela e alegria. É o espírito de doce amizade que brilha todo o ano. É consideração e bondade, é a esperança renascida novamente, para paz, para entendimento e para benevolência dos homens.", "autor": "Desconhecido", "likes": 88, "liked": false, "comments": 88, "retweets": 22},
    {"frase": "Não há alegria pública que valha uma boa alegria particular.", "autor": "Machado de Assis", "likes": 93, "liked": false, "comments": 32, "retweets": 3},
    {"frase": "Feliz na tristeza, triste na alegria.", "autor": "Giordano Bruno", "likes": 86, "liked": false, "comments": 23, "retweets": 23},
    {"frase": "A alegria do pobre, ainda que menos durável, é sempre mais intensa que a do rico.", "autor": "Marquês de Maricá", "likes": 52, "liked": false, "comments": 57, "retweets": 49},
    {"frase": "Toda a educação, no momento, não parece motivo de alegria, mas de tristeza. Depois, no entanto, produz naqueles que assim foram exercitados um fruto de paz e de justiça.", "autor": "Textos Bíblicos", "likes": 50, "liked": true, "comments": 12, "retweets": 2},
    {"frase": "Toda a alegria vem do amor, e todo o amor inclui o sofrimento.", "autor": "Abílio Guerra Junqueiro", "likes": 15, "liked": false, "comments": 44, "retweets": 98},
    {"frase": "O trabalho só nos cansa se não nos dedicarmos a ele com alegria.", "autor": "Rabindranath Tagore", "likes": 31, "liked": false, "comments": 54, "retweets": 48},
    {"frase": "A tristeza pura é tão impossível como a alegria pura.", "autor": "Leon Tolstói", "likes": 71, "liked": false, "comments": 23, "retweets": 83},
    {"frase": "A criança é alegria como o raio de sol e estímulo como a esperança.", "autor": "Coelho Neto", "likes": 72, "liked": false, "comments": 16, "retweets": 25},
    {"frase": "No amor alternam a alegria e a dor.", "autor": "Lord Byron", "likes": 12, "liked": false, "comments": 94, "retweets": 56},
    {"frase": "A alegria é a pedra filosofal que tudo converte em ouro.", "autor": "Benjamin Franklin", "likes": 83, "liked": false, "comments": 63, "retweets": 83},
    {"frase": "A alegria só pode brotar de entre as pessoas que se sentem iguais.", "autor": "Honoré de Balzac", "likes": 41, "liked": false, "comments": 63, "retweets": 52},
    {"frase": "Terás alegria ou terás poder, disse Deus; mas não terás ambos.", "autor": "Ralph Waldo Emerson", "likes": 63, "liked": false, "comments": 85, "retweets": 40},
    {"frase": "A única alegria no mundo é começar. É bom viver porque viver é começar sempre, a cada instante.", "autor": "Cesare Pavese", "likes": 45, "liked": false, "comments": 42, "retweets": 14},
    {"frase": "A alma que não se abate, que recebe indiferentemente tanto a tristeza como a alegria, vive na vida imortal.", "autor": "Textos Hindus", "likes": 22, "liked": false, "comments": 75, "retweets": 51},
    {"frase": "A alegria não está nas coisas, mas em nós.", "autor": "Charles Wagner", "likes": 16, "liked": false, "comments": 54, "retweets": 54},
    {"frase": "A alegria torna o homem sociável, a dor individualiza-o.", "autor": "Christian Hebbel", "likes": 68, "liked": false, "comments": 14, "retweets": 81},
    {"frase": "O desgosto pode tomar conta de si próprio, mas para tirar todo o partido de uma alegria, temos de ter alguém com quem a partilhar.", "autor": "Mark Twain", "likes": 37, "liked": true, "comments": 52, "retweets": 20},
    {"frase": "Se um sacrifício é uma tristeza para ti, e não uma alegria, então não o faças, não és digno dele.", "autor": "Romain Rolland", "likes": 82, "liked": false, "comments": 8, "retweets": 65},
    {"frase": "A alegria e a tristeza são duas prisões; uma de ouro e outra de ferro, mas feitas igualmente para nos prender e impedir de seguir a nossa verdadeira natureza.", "autor": "Swami Vivekananda", "likes": 95, "liked": false, "comments": 29, "retweets": 91},
    {"frase": "Pode-se ficar alegre consigo mesmo durante certo tempo, mas a longo prazo a alegria tem de ser compartilhada por duas pessoas.", "autor": "Henrik Ibsen", "likes": 46, "liked": false, "comments": 7, "retweets": 3},
    {"frase": "A vida é em geral alegre. O que nos torna injustos em relação a ela é que a alegria não é recordada. Ao contrário, a inquietude, essa, permanece.", "autor": "Jean Paulhan", "likes": 44, "liked": true, "comments": 71, "retweets": 35},
    {"frase": "Nenhum bem sem um companheiro nos dá alegria.", "autor": "Sêneca", "likes": 67, "liked": true, "comments": 14, "retweets": 94},
    {"frase": "A energia é a eterna alegria.", "autor": "William Blake", "likes": 93, "liked": false, "comments": 23, "retweets": 69},
    {"frase": "Há uma alegria selvagem em estar vivo. Há uma embriaguez da existência. Cada hora é uma amante para o meu desejo infinito.", "autor": "Arthur Lundkvist", "likes": 1, "liked": false, "comments": 84, "retweets": 56},
    {"frase": "A mais nobre alegria dos homens que pensam é haverem explorado o concebível e reverenciarem em paz o incognoscível.", "autor": "Johann Goethe", "likes": 24, "liked": true, "comments": 31, "retweets": 75},
    {"frase": "A minha alegria é a melancolia.", "autor": "Michelangelo", "likes": 30, "liked": true, "comments": 42, "retweets": 73},
    {"frase": "A alegria intensa é recolher-se e calar-se. Falar é dispersar.", "autor": "Henri Amiel", "likes": 78, "liked": false, "comments": 36, "retweets": 60},
    {"frase": "O amor é a alegria acompanhada da ideia de uma causa exterior.", "autor": "Baruch Espinoza", "likes": 10, "liked": true, "comments": 60, "retweets": 21},
    {"frase": "Sendo todas as outras coisas iguais, o desejo que nasce da alegria é mais forte que o desejo que nasce da tristeza.", "autor": "Baruch Espinoza", "likes": 70, "liked": true, "comments": 97, "retweets": 38},
    {"frase": "Há na sensualidade uma espécie de alegria cósmica.", "autor": "Jean Giono", "likes": 43, "liked": false, "comments": 45, "retweets": 83},
    {"frase": "O homem hoje, para ser salvo, só tem necessidade de uma coisa: abrir o coração à alegria.", "autor": "Bertrand Russell", "likes": 25, "liked": false, "comments": 17, "retweets": 0},
    {"frase": "O que quer que seja que estejamos esperando - paz de espírito, alegria, graça, consciência interior ou simples abundância - isso certamente virá para nós, mas somente quando estivermos prontos para receber com um coração aberto e agradecido.", "autor": "Sarah Ban Breathnach", "likes": 27, "liked": true, "comments": 16, "retweets": 88},
    {"frase": "A alegria é para o corpo humano o mesmo que o sol é para as plantas.", "autor": "Jean Massillon", "likes": 4, "liked": true, "comments": 48, "retweets": 79},
    {"frase": "Fazer poesia é como fazer amor: nunca se saberá se a própria alegria é compartilhada.", "autor": "Cesare Pavese", "likes": 28, "liked": false, "comments": 38, "retweets": 55},
    {"frase": "O desgosto e a alegria dependem mais do que somos do que daquilo que nos acontece..", "autor": "Multatuli", "likes": 62, "liked": false, "comments": 62, "retweets": 7},
    {"frase": "A alegria e o trabalho são duas coisas sãs e que atraem reciprocamente.", "autor": "Ernest Renan", "likes": 38, "liked": false, "comments": 64, "retweets": 85},
    {"frase": "Quando a alegria se torna tristeza e o bem-estar infortúnio, as almas pacientes extrairão prazer mesmo da dor.", "autor": "Textos Budistas", "likes": 16, "liked": false, "comments": 67, "retweets": 16},
    {"frase": "Há poucas coisas tão fatalmente contagiosas como a alegria das pessoas sérias.", "autor": "Júlio Dinis", "likes": 39, "liked": false, "comments": 0, "retweets": 68},
    {"frase": "Quem faz com alegria e se alegra com o efectuado é feliz.", "autor": "Johann Goethe", "likes": 27, "liked": true, "comments": 87, "retweets": 41},
    {"frase": "Não há alegria neste mundo tão privilegiada, que não pague pensão à tristeza.", "autor": "Padre Antônio Vieira", "likes": 18, "liked": false, "comments": 19, "retweets": 90},
    {"frase": "Toda a beleza é alegria que permanece.", "autor": "John Keats", "likes": 35, "liked": false, "comments": 14, "retweets": 38},
    {"frase": "Nós, poetas, na nossa mocidade começamos com alegria, / Mas daí passamos finalmente ao desalento e à loucura.", "autor": "William Wordsworth", "likes": 88, "liked": false, "comments": 68, "retweets": 50},
    {"frase": "Espalhe para todos a alegria que vive dentro de você.", "autor": "Desconhecido", "likes": 92, "liked": false, "comments": 20, "retweets": 84}
  ];
}
